version: '3'

services:
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    ports:
      - 4040:4040
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    networks:
      - slack-app_network
  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 3000:3000
    networks:
      - slack-app_network
networks:
  slack-app_network:
    driver: bridge
